let stockProductos = [
    {id: 1, nombre: "Pokemon Lets go Eevee", cantidad: 1, desc: "RPG de pokemon", precio: 12000, tipo: "Videojuego", img: './img/pokemonletsgoeevee.png'},
    {id: 2, nombre: "Pokemon Sword", cantidad: 1, desc: "Videojuego de rol en el universo pokemon", precio: 8000, tipo: "Videojuego", img: './img/pokemonsword.jpg'},
    {id: 3, nombre: "ARK", cantidad: 1, desc: "Acción-aventura y supervivencia", precio: 9000, tipo: "Videojuego", img: './img/ark.jpg'},
    {id: 4, nombre: "Pokemon Legends Arceus", cantidad: 1, desc: "Videojuego de rol y accion en el universo pokemon", precio: 4000, tipo: "Videojuego", img: './img/pokemonlegendsarceus.jpg'},
    {id: 5, nombre: "Back4Blood", cantidad: 1, desc: "Shooter zombie en primera persona de accion frenetica", precio: 10000, tipo: "Videojuego", img: './img/back4blood.jpg'},
    {id: 6, nombre: "Batman Arkham Knight", cantidad: 1, desc: "Accion-aventura de mundo abierto", precio: 8000, tipo: "Videojuego", img: './img/batmanarkhamknight.jpg'},
    {id: 7, nombre: "Battlefield 5", cantidad: 1, desc: "Shooter multijugador en primera persona", precio: 6000, tipo: "Videojuego", img: './img/battlefield5.jpg'},
    {id: 8, nombre: "Battlefield 2042", cantidad: 1, desc: "Shooter multijugador en primera persona", precio: 6000, tipo: "Videojuego", img: './img/battlefield2042.jpg'},
    {id: 9, nombre: "Bladestorm", cantidad: 1, desc: "Videojuego histórico de tácticas en tiempo real", precio: 3000, tipo: "Videojuego", img: './img/bladestorm.jpg'},
    {id: 10, nombre: "Call of duty: Cold war", cantidad: 1, desc: "Shooter multijugador en primera person", precio: 11000, tipo: "Videojuego", img: './img/codcoldwar.jpg'},
    {id: 11, nombre: "Call of duty: Vanguard", cantidad: 1,desc: "Shooter multijugador en primera persona", precio: 11000, tipo: "Videojuego", img: './img/codvanguard.jpg'},
    {id: 12, nombre: "Cyberpunk 2077", cantidad: 1, desc: "Shooter de rol y aventura en primera persona", precio: 12000, tipo: "Videojuego", img: './img/cyberpunk2077.jpg'},
    {id: 13, nombre: "Dark Souls Remastered", cantidad: 1, desc: "Videojuego de rol y accion para los mas expertos", precio: 8000, tipo: "Videojuego", img: './img/darksoulsremaster.jpg'},
    {id: 14, nombre: "Death Stranding", cantidad: 1, desc: "Accion y exploracion en mundo abierto", precio: 10000, tipo: "Videojuego", img: './img/deathstranding.jpg'},
    {id: 15, nombre: "Dragon Age Inquisition", cantidad: 1, desc: "RPG de fantasia medieval", precio: 7000, tipo: "Videojuego", img: './img/dragonageinquisition.jpg'},
    {id: 16, nombre: "Dying Light 2", cantidad: 1, desc: "Accion y aventura zombie en primera persona", precio: 6500, tipo: "Videojuego", img: './img/dyinglight2.jpg'},
    {id: 17, nombre: "Fallout 76", cantidad: 1, desc: "Multijugador de rol y accion", precio: 5000, tipo: "Videojuego", img: './img/fallout76.jpg'},
    {id: 18, nombre: "God of war", cantidad: 1, desc: "Videojuego de accion y aventura", precio: 10000, tipo: "Videojuego", img: './img/godofwar.jpg'},
    {id: 19, nombre: "Joystick ps4", cantidad: 1, desc: "Control para PS4", precio: 30000, tipo: "Accesorio", img: './img/joystickps4.jpg'},
    {id: 20, nombre: "Joystick ps4 camuflado", cantidad: 1, desc: "Control para PS4 camuflado", precio: 32000, tipo: "Accesorio", img: './img/joystickps4camuflado.jpg'},
    {id: 21, nombre: "Auriculares Redragon Lamia", cantidad: 1, desc: "Auriculares gaming", precio: 15000, tipo: "Accesorio", img: './img/auricularlamia.jpg'},
    {id: 22, nombre: "Auriculares Redragon Ares", cantidad: 1, desc: "Auriculares gaming", precio: 18500, tipo: "Accesorio", img: './img/auricularares.jpg'},
    {id: 23, nombre: "Playstation 4", cantidad: 1, desc: "Consola gaming de Sony", precio: 90000, tipo: "Consola", img: './img/ps4.jpg'},
    {id: 24, nombre: "Xbox One", cantidad: 1, desc: "Consola gaming de Microsoft", precio: 98000, tipo: "Consola", img: './img/xboxone.jpg'},
]